### ISSUE TITLE
LLVM code gen failure causing compiler crash with defer(os.exit(0)) and early return

### ISSUE THREAD

**Issue by thePHTest** [odin-lang/Odin#3216] opened 2024-02-21 04:47 UTC
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System & Odin Version:
Odin: dev-2024-02:c5c2a4d09
        OS:   Windows 11 Home Basic (version: 22H2), build 22621.2861
        CPU:  11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
        RAM:  32602 MiB

## Expected Behavior

Compiles successfully or a proper error if this shouldn't be allowed

## Current Behavior

LLVM code gen failure

## Failure Information (for bugs)

# odin build .                                                                   
LLVM CODE GEN FAILED FOR PROCEDURE: main.main                                    
define internal void @main.main(ptr noalias nocapture nonnull %__.context_ptr) { 
decls:                                                                           
  %x = alloca i64, align 8                                                       
  br label %entry                                                                
                                                                                 
entry:                                            ; preds = %decls               
  store i64 1, ptr %x, align 8                                                   
  %0 = load i64, ptr %x, align 8                                                 
  %1 = icmp sgt i64 %0, 1                                                        
  %2 = zext i1 %1 to i8                                                          
  %3 = icmp ne i8 %2, 0                                                          
  br i1 %3, label %if.then, label %if.done                                       
                                                                                 
if.then:                                          ; preds = %entry               
  br label %defer                                                                
                                                                                 
defer:                                            ; preds = %if.then             
  call void @os.exit(i64 0)                                                      
  unreachable                                                                    
  ret void                                                                       
                                                                                 
if.done:                                          ; preds = %entry               
  br label %defer1                                                               
                                                                                 
defer1:                                           ; preds = %if.done             
  call void @os.exit(i64 0)                                                      
  unreachable                                                                    
}                                                                  
                                                         
Terminator found in the middle of a basic block!                                 
label %defer

**Comment by laytan** [comment] 2024-02-21 08:46
Duplicate of #2985

**Closed** 2024-02-21 18:53 UTC
