### ISSUE TITLE
Compiler crashes when building with spall

### ISSUE THREAD

**Issue by laughsuggestion** [odin-lang/Odin#3970] opened 2024-07-23 17:58 UTC
## Context

```
package main

import "base:runtime"
import spall "core:prof/spall"

import "core:fmt"
spall_ctx: spall.Context
spall_buffer: spall.Buffer

@(instrumentation_enter)
spall_enter :: proc "contextless" (
    proc_address, call_site_return_address: rawptr,
    loc: runtime.Source_Code_Location,
) {
    spall._buffer_begin(&spall_ctx, &spall_buffer, "", "", loc)
}

@(instrumentation_exit)
spall_exit :: proc "contextless" (
    proc_address, call_site_return_address: rawptr,
    loc: runtime.Source_Code_Location,
) {
    spall._buffer_end(&spall_ctx, &spall_buffer)
}

main :: proc() {
    fmt.printfln("hello, world!")
}
```

```
Odin:    dev-2024-07:527c0b320
	OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
	CPU:     Apple M2 Pro
	RAM:     16384 MiB
	Backend: LLVM 14.0.6
```

## Expected Behavior

Running "odin build" should build successfully.

## Current Behavior

The compiler crashes.

## Failure Information (for bugs)

The compiler crashes and outputs an error.

### Steps to Reproduce

1. Run: odin build src/

### Failure Logs

`35747 bus error  odin build src/`

**Comment by laytan** [comment] 2024-07-23 23:41
Unfortunately, I can't reproduce this on:
```
Where to find more information and get into contact when you encounter a bug:

	Website: https://odin-lang.org
	GitHub:  https://github.com/odin-lang/Odin/issues


Useful information to add to a bug report:

	Odin:    dev-2024-07:f9ef951b2
	OS:      macOS Sonoma 14.5 (build: 23F79, kernel: 23.5.0)
	CPU:     Apple M1
	RAM:     8192 MiB
	Backend: LLVM 18.1.4
```

Maybe it is the LLVM version difference, let me check.

**Comment by laytan** [comment] 2024-07-23 23:42
Ah yep, that's it, I reproduce this on LLVM 14.

**Comment by laytan** [comment] 2024-07-24 00:14
Ok the reason for the bus error was an error message over 4kb not fitting on the stack buffer used for printing it, here is the first snippet of that error message:
```
LLVM Error:
Call parameter type does not match function signature!
i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq
 i8*  call void @main.spall_enter(i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq, i8* %4, %runtime.Source_Code_Location* @"ggv$1f2")
Call parameter type does not match function signature!
i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq
 i8*  call void @main.spall_exit(i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq, i8* %4, %runtime.Source_Code_Location* @"ggv$1f3")
Call parameter type does not match function signature!
i8 (i8*, i8*, i64)* @runtime.memory_equal
 i8*  call void @main.spall_enter(i8 (i8*, i8*, i64)* @runtime.memory_equal, i8* %23, %runtime.Source_Code_Location* @"ggv$1b8")
Call parameter type does not match function signature!
i8 (i8*, i8*, i64)* @runtime.memory_equal
 i8*  call void @main.spall_exit(i8 (i8*, i8*, i64)* @runtime.memory_equal, i8* %23, %runtime.Source_Code_Location* @"ggv$1b9")
Call parameter type does not match function signature!
i8 (i8*, i8*, i64)* @runtime.memory_equal
 i8*  call void @main.spall_exit(i8 (i8*, i8*, i64)* @runtime.memory_equal, i8* %23, %runtime.Source_Code_Location* @"ggv$1ba")
Call parameter type does not match function signature!
i8 (i8*, i8*, i64)* @runtime.memory_equal
 i8*  call void @main.spall_exit(i8 (i8*, i8*, i64)* @runtime.memory_equal, i8* %23, %runtime.Source_Code_Location* @"ggv$1bb")
Call parameter type does not match function signature!
i8 (i8*, i8*, i64)* @runtime.memory_equal
 i8*  call void @main.spall_exit(i8 (i8*, i8*, i64)* @runtime.memory_equal, i8* %23, %runtime.Source_Code_Location* @"ggv$1bc")
Call parameter type does not match function signature!
i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq
 i8*  call void @main.spall_exit(i8 (<{ i64, i64 }>, <{ i64, i64 }>)* @runtime.string_eq, i8* %4, %runtime.Source_Code_Location* @"ggv$1f4")
Call parameter type does not match function signature!
void (i8*)* @runtime._destroy_temp_allocator_fini-3953
 i8*  call void @main.spall_enter(void (i8*)* @runtime._destroy_temp_allocator_fini-3953, i8* %0, %runtime.Source_Code_Location* @"ggv$ae")
Call parameter type does not match function signature!
void (i8*)* @runtime._destroy_temp_allocator_fini-3953
 i8*  call void @main.spall_exit(void (i8*)* @runtime._destroy_temp_allocator_fini-3953, i8* %0, %runtime.Source_Code_Location* @"ggv$af")
Call parameter type does not match function signature!
<{ i64, i64 }> (i32, i8*)* @os.stream_from_handle
 i8*  call void @main.spall_enter(<{ i64, i64 }> (i32, i8*)* @os.stream_from_handle, i8* %2, %runtime.Source_Code_Location* @"ggv$44")
Call parameter type does not match function signature!
<{ i64, i64 }> (i32, i8*)* @os.stream_from_handle
 i8*  call void @main.spall_exit(<{ i64, i64 }> (i32, i8*)* @os.stream_from_handle, i8* %2, %runtime.Source_Code_Location* @"ggv$45")
Call parameter type does not match function signature!
<{ i64, i64 }> (i8*)* @runtime.heap_allocator
 i8*  call void @main.spall_enter(<{ i64, i64 }> (i8*)* @runtime.heap_allocator, i8* %1, %runtime.Source_Code_Location* @"ggv$46")
Call parameter type does not match function signature!
<{ i64, i64 }> (i8*)* @runtime.heap_allocator
 i8*  call void @main.spall_exit(<{ i64, i64 }> (i8*)* @runtime.heap_allocator, i8* %1, %runtime.Source_Code_Location* @"ggv$47")
Call parameter type does not match function signature!
i128 (i128, i128, i128*)* @runtime.udivmod128
 i8*  call void @main.spall_enter(i128 (i128, i128, i128*)* @runtime.udivmod128, i8* %5, %runtime.Source_Code_Location* @"ggv$48")
Call parameter type does not match function signature!
i128 (i128, i128, i128*)* @runtime.udivmod128
 i8*  call void @main.spall_exit(i128 (i128, i128, i128*)* @runtime.udivmod128, i8* %5, %runtime.Source_Code_Location* @"ggv$49")
Call parameter type does not match function signature!
i128 (i128, i128, i128*)* @runtime.udivmod128
 i8*  call void @main.spall_exit(i128 (i128, i128, i128*)* @runtime.udivmod128, i8* %5, %runtime.Source_Code_Location* @"ggv$4a")
Call parameter type does not match function signature!
i128 (i128%
```

**Comment by laytan** [comment] 2024-07-24 00:45
Should be fixed now

**Closed** 2024-07-24 00:44 UTC
