### ISSUE TITLE
Misnamed LLVM lib on linux in 2024-08 release

### ISSUE THREAD

**Issue by justinian** [odin-lang/Odin#4125] opened 2024-08-23 17:25 UTC
## Context

I'm new to Odin and downloaded the linux version to check it out. Odin failed to run due to a missing reference to `libLLVM-18.so.18.1`. The LLVM lib provided in the zipfile is named `libLLVM-18.so.1`. Renaming and/or symlinking the shared library resolves the issue.

* Operating System & Odin Version: Debian testing (under WSL2), Odin 
* Please paste `odin report` output:

```
        Odin:    dev-2024-08-nightly:8359995
        OS:      Debian GNU/Linux trixie/sid, Linux 5.15.153.1-microsoft-standard-WSL2
        CPU:     AMD Ryzen 9 7950X 16-Core Processor
        RAM:     31659 MiB
        Backend: LLVM 18.1.8
```
(once lib is renamed) 

## Expected Behavior

User does not have to rename library file when downloading a release.

## Current Behavior

Library file is misnamed.

## Failure Information (for bugs)

Running `./odin` fails in the dynamic loader:
```
./odin: error while loading shared libraries: libLLVM-18.so.18.1: cannot open shared object file: No such file or directory
```

Running `ldd ./odin` shows the missing lib as well:
```
        linux-vdso.so.1 (0x00007ffe6d5e5000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f45ee8e3000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f45ee67e000)
        libLLVM-18.so.18.1 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f45ee651000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45ee468000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f45eec81000)
```

Contents of the zip:
```
justin@Jove > unzip -lv odin-ubuntu-amd64-dev-2024-08.zip 'dist/lib*'                                                                                               [Fri 10:22:51]
Archive:  odin-ubuntu-amd64-dev-2024-08.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
123362536  Defl:N 37882967  69% 2024-08-01 13:09 ee423abc  dist/libLLVM-18.so.1
--------          -------  ---                            -------
123362536         37882967  69%                            1 file
```

### Steps to Reproduce

1. Download `odin-ubuntu-amd64-dev-2024-08.zip` and unzip on linux
2. Attempt to run the `odin` binary from `dist/`

**Comment by laytan** [comment] 2024-08-23 18:40
Duplicate of #4033 and #4019 and I think this has been fixed for the next release, thanks for taking the time to file an issue though!

**Closed by laytan** 2024-08-23 18:40 UTC
