### ISSUE TITLE
LLVM Error: Invalid bitcast

### ISSUE THREAD

**Issue by Hyp-X** [odin-lang/Odin#2522] opened 2023-05-09 11:24 UTC
## Context

Odin: dev-2023-05:29e47620
OS:   Windows 11 Professional (version: 22H2), build 22622.575
CPU:  AMD Ryzen 5 5600X 6-Core Processor
RAM:  32689 MiB

## Current Behavior

Compile fails with:
```
LLVM Error:
Invalid bitcast
%main.TextureParams bitcast ({ i32, i32, i32, [4 x i8], i64, i32, [4 x i8], i64 } { i32 0, i32 0, i32 0, [4 x i8] zeroinitializer, i64 0, i64 8709, [4 x i8] zeroinitializer, i64 0 } to %main.TextureParams)
```

## Steps to Reproduce

```odin
package main

import "core:fmt"

TextureFormat :: enum {
	D32_float          = 0x2205,
}

TextureDimension :: enum {
	Texture2D,
	TextureCube,
}

TextureParams :: struct {
	width: u32,
	height: u32,
	arraySize: u32,
	dimension: TextureDimension,
	mipmapCount: u32,
	format: TextureFormat,
}

CreateRenderTextureParams :: struct {
	using paramsBase: TextureParams,
	name: string,
}

CreateRenderTexture :: proc(params: CreateRenderTextureParams)
{
}

main :: proc() 
{
	CreateRenderTexture({
		name = "primaryDepthBuffer",
		format = .D32_float,
	})
	fmt.printf("Hello world\n")
}
```

With `odin run .`

**Comment by Devastus** [comment] 2023-05-25 21:46
Odin: master:93713252 (newest, compiled with LLVM 15)
OS: Void Linux (x64, gcc)

I was able to reproduce this with a tad shorter example on Linux too:

```odin
package main

import "core:fmt"

TypeA :: struct {
    fa: [3]f32,
    fb: [3]f32,
    fc: [3]f32,
}

anon_struct := struct {
    container1: struct {
        a: f32,
        b: string,
    },
    container2: struct {
        a: i32,
        b: bool,
        using c: TypeA,
    },
}{}

main :: proc() {
    anon_struct = {
        container1 = { b = "hello" },
        container2 = { fa = {1, 2, 3} },
    }
    fmt.printf("%v\n", anon_struct.container2.fa)
}
```

Results in:
```sh
LLVM Error:
Invalid bitcast
%main.TypeA bitcast ({ [3 x float], [3 x float], [3 x float] } { [3 x float] [float 1.000000e+00, float 2.000000e+00, float 3.000000e+00], [3 x float] zeroinitializer, [3 x float] zeroinitializer } to %main.TypeA)
```

Removing some of the fields turns the response into a simple `Segmentation fault` or `Illegal instruction` upon running.

**Comment by bolducke** [comment] 2023-05-28 02:02
Odin: dev-2023-04:019cf1e
OS:   Unknown Linux Distro, Linux 6.3.4-arch1-1
CPU:  12th Gen Intel(R) Core(TM) i7-12700H
RAM:  15719 MiB

I had the same error in my project. I remove all usage of `using` and it fix my issue. I observe similar behavior as Devastus.

**Comment by Devastus** [comment] 2023-05-29 10:52
Just to elaborate a bit, the error occurrence seems to be specifically related to the initialization of struct fields. Here's a working example (took out anonymous structs just in case):

```odin
package main

import "core:fmt"

TypeA :: struct {
    aa, ab, ac: [3]f32,
}

TypeB :: struct {
    ba: i32,
    bb: string,
}

TypeC :: struct {
    ca: f32,
    cb: bool,
    using cc: TypeA,
}

TypeF :: struct {
    fa: TypeB,
    fb: TypeC,
}

main :: proc() {
    test := TypeF{
        fb = { cc = { aa = {1, 2, 3} } },
    }
    fmt.printf("aa: %v\n", test.fb.aa)
}
```

This one works as-is and prints the value correctly, as we initialize the **cc**-field explicitly (but later use its member field "implicitly").

If we change the struct initialization to take advantage of the using-syntax, ie. declaring it's member in the parent struct, we'll get the same error as before: `fb = { aa = {1, 2, 3} },`

Hopefully this provides some clues as to where the problem actually resides.

**Comment by gingerBill** [comment] 2023-06-07 14:52
This should be fixed now.

**Closed by gingerBill** 2023-06-07 14:52 UTC
