### ISSUE TITLE
Compiler crashes on polymorphic procedure-type parameter overriden from default value in call.

### ISSUE THREAD

**Issue by zargy** [odin-lang/Odin#486] opened 2019-11-29 04:48 UTC
## Context
* Operating System: Windows 7 64-Bit
* Odin version/Commit: 0.11.1 (11/21/2019 2:05:45 PM, 45d844f9d2f3791bd4dd06724d6835a6a6ebd2c4)

The compiler crashes when:
- I create a procedure with a parameter of type polymorphic procedure, and provide a default value.
- I call that procedure and override the default parameter.

## Reproduction Code:
```package test

using import "core:fmt"

Entity 	:: struct { name : string };
Frog 	:: struct {
    using entity: Entity,
    ribbit_volume: f32,
}

print_base :: proc(using a : ^Entity) 	{ println("Entity is named", name); 						  	  }
print_frog :: proc(using a : ^Frog) 	{ println("Frog", name, "has a ribbit volume of", ribbit_volume); }

//Everything works fine if I do like so:
//print_entity :: proc(e : ^Entity, p : proc($T)) { p(cast(T)e); }

print_entity :: proc(e : ^Entity, p : proc($T) = print_base) { p(cast(T)e); }

main :: proc()
{
	f : Frog;
	f.name = "Prince Charming";
	f.ribbit_volume = 20.5;
	
	//Works fine
	print_entity(&f);
	
	//Doesn't work fine, crashes when compiling
	print_entity(&f, print_frog);
}
```

The app crashes with this problem signature:
```Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	odin.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5dd96a19
  Fault Module Name:	odin.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5dd96a19
  Exception Code:	c0000005
  Exception Offset:	0000000000064aa4
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	1084
  Additional Information 2:	10844a350a6efc96fb72ef45e8981dd2
  Additional Information 3:	6584
  Additional Information 4:	6584cfac084bdff9f2be12d813fe07e6```

**Comment by gingerBill** [comment] 2019-12-01 16:06
The crash was caused by nothing related to this but it is now fixed and it does show an error now. Even if that error may be wrong.

I will have to think about if this is a bug or not.

**Comment by zargy** [comment] 2019-12-01 21:58
I'm glad the crash is fixed. I'm not sure why it shouldn't be allowed, if that's what you're thinking about. If you allow poly procedures as parameters it makes sense that you should be able to set defaults and override them.

**Comment by gingerBill** [comment] 2019-12-02 10:18
It probably should be allowed. It should not be too difficult to fix.

**Comment by oskarnp** [comment] 2020-03-21 14:51
Similar issue:

```
Write :: proc(buf: ^ByteBuffer, v: $T) {}
EncodeList :: proc(buf: ^ByteBuffer, t: []$T, enc: proc(^ByteBuffer, T) = Write) {}
```
Causes error `Redeclaration of 'T' in this scope`.

Changing to:


```
Write :: proc(buf: ^ByteBuffer, v: $S) {}
EncodeList :: proc(buf: ^ByteBuffer, t: []$T, enc: proc(^ByteBuffer, T) = Write) {}
```
Causes:

```
src/ir_print.cpp(1255): Assertion Failure: `found != nullptr`
zsh: illegal hardware instruction  odin run test.odin
```

**Comment by bttelle** [comment] 2020-09-15 08:43
For anyone wanting to use defaults for `parapoly` parameters that runs into the behavior at the top of this issue, you can implement defaults with a mixture of implicit and explicit parametric polymorphism.  Here is a workaround to get the example code at the top to compile correctly:
```odin
print_entity :: proc{print_entity_base, print_entity_poly};
print_entity_base :: proc(e : ^Entity) { print_entity(e, print_base); } /* default */
print_entity_poly :: proc(e : ^Entity, p : proc($T)) { p(cast(T)e); }
```
There are other advantages to this approach like being able to use defaults that aren't constants.

**Comment by bttelle** [comment] 2020-09-16 19:42
With PR #739 besides this being valid now:
```odin
print_entity :: proc(e : ^Entity, p : proc($T) = print_base) { p(cast(T)e); }
```
you can also rephrase it without the cast for more type safety:
```odin
print_entity :: proc(e : ^$E, p : proc(^$T) = print_base) { p(e); }
```

**Comment by gingerBill** [comment] 2020-09-16 21:23
Does this need to be closed now?

**Comment by bttelle** [comment] 2020-09-17 01:19
Yes, it can be closed in my view.

**Comment by Tetralux** [comment] 2020-09-17 02:28
Just tested this; here's a crash repro on current [master](https://github.com/odin-lang/Odin/commit/10afc58d7d5e119f3b9332deb28bcd0d77caa089):

@gingerBill @bttelle 

```odin
// Error message: src\ir_print.cpp(1307): Assertion Failure: `found != nullptr` null_fn

main :: proc() {
    using fmt;

    null_fn :: proc(arg: ^$T) {
        fmt.println("null_fn: ", arg);
    }

    f :: proc(arg: ^$T, fn: proc(^$U) = null_fn) {
        fn(arg);
    }

    i := 44;
    
    //
    // Works
    //
    f(&i, proc(x: ^int) {
        println("call to f: ", x^);
    });

    //
    // Doesn't work
    //
    // f(&i);
}
```
And here's an error that makes no sense:
```odin

// Error message: `Redeclaration of 'T' in this scope` pointing to the two `$T`s.

main :: proc() {
    using fmt;

    null_fn :: proc(arg: ^$T) {
        fmt.println("null_fn: ", arg);
    }

    // NOTE: second T is not a new variable
    g :: proc(arg: ^$T, fn: proc(^T) = null_fn) {
        fn(arg);
    }

    i := 44;
    
    //
    // Either of these calls cause the same problem
    //

    g(&i);
    g(&i, proc(x: ^int) {
        println("call to f: ", x^);
    });
}
```

**Comment by bttelle** [comment] 2020-09-17 06:18
@Tetralux This reduced code without the polymorphic defaults causes the assert for me.  I'll check if it happened before my commit as well.
```odin
package main
import "core:fmt"
main :: proc() {
    using fmt;
    null_fn :: proc(arg: ^$T) {
        fmt.println("null_fn: ", arg);
    }
    i := 44;    
    null_fn(&i);
}
```

**Comment by bttelle** [comment] 2020-09-17 06:31
So this:
>// Error message: src\ir_print.cpp(1307): Assertion Failure: `found != nullptr` null_fn

happens with this same code  prior to my commit #739 as well.  It is a separate issue that is triggered by the defaulted procedure itself taking a polymorphic parameter.  I'll look into it and we can just keep this issue open until I find a solution.

If you change ```null_fn :: proc(arg: ^$T)`` to ```null_fn :: proc(arg: ^int)``` the defaulted procedure works fine.

**Comment by bttelle** [comment] 2020-09-17 07:02
This is the smallest reproducer:
```odin
package main
null_fn :: proc(arg : ^$T) {}
f :: proc(fn : proc(^int) = null_fn) {}
main :: proc() {
    f();
}
```

**Comment by Tetralux** [comment] 2020-09-17 16:38
@bttelle Made a [separate issue](https://github.com/odin-lang/Odin/issues/741) for the other one since it's not a crash.

**Comment by wilsonk** [comment] 2021-04-28 12:10
On Win10 with Odin version dev-4-28-1-:94fd59e6 (after old backend removal), the original code at the top of this issue works. @Tetralux first example gives me this error now:
```
C:\Users\wilsonk\odin\src\llvm_backend.cpp(5697): Panic: Error in: C:/Users/wilsonk/odin/mine/issue-486.odin(36:2), missing procedure null_fn
```
His second example gives:
```
C:/Users/wilsonk/odin/mine/issue-486.odin(10:25) Redeclaration of 'T' in this scope at C:/Users/wilsonk/odin/mine/issue-486.odin(15:19)
```
Which is similar but not quite exactly the same error.  And the example from bttelle produces:
```
C:\Users\wilsonk\odin\src\llvm_backend.cpp(5697): Panic: Error in: C:/Users/wilsonk/odin/mine/issue-486.odin(65:2), missing procedure null_fn
``` 
again.

**Comment by gingerBill** [comment] 2021-04-28 12:12
@wilsonk Please check against the latest commit. All of these bugs are gone.

**Closed** 2021-04-28 13:16 UTC
Labels: bug, discussion
