### ISSUE TITLE
`odin run something_invalid.odin -file` silently fails

### ISSUE THREAD

**Issue by jakubtomsu** [odin-lang/Odin#3661] opened 2024-06-02 20:04 UTC
## Context

When I run `odin run asljkdfjasdf.odin -file` the compiler silently fails and doesn't print anything, which can be confusing in case a typo in the path happens.

```
        Odin:    dev-2024-06:c07a46abc
        OS:      Windows 10 Professional (version: 22H2), build 19045.4412
        CPU:     Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
        RAM:     32681 MiB
        Backend: LLVM 17.0.1
```

## Expected Behavior
The compiler should print an error, similar to what regular `odin run` without `-file` does:
```
odin run asljkdfjasdf
ERROR: `odin run` takes a package as its first argument.
Did you mean `odin run asljkdfjasdf -file`?
The `-file` flag tells it to treat a file as a self-contained package
```

**Comment by Feoramund** [comment] 2024-06-02 20:52
Not quite an _exact_ duplicate of #3660, but this case is also addressed in #3662.

**Closed** 2024-06-02 21:22 UTC
