### ISSUE TITLE
Returning 'any' from a function gives garbage

### ISSUE THREAD

**Issue by dsemi** [odin-lang/Odin#3073] opened 2024-01-07 00:09 UTC
## Repro

`test.odin`:
```
package main

import "core:fmt"

test :: proc() -> any {
  num: int = 0
  return num
}

main :: proc() {
  num: int = 0
  fmt.println(num)
  fmt.println(test())
}
```

Run with `odin run test.odin -file`

### Expected Behavior

The program should print:
```
0
0
```

### Current Behavior

The program prints:
```
0
4339330516 // Or some other random number
```

## Additional information
I can reproduce with other types besides `int` as well, e.g. `string` panics with `Invalid slice indices ...`

## Context

* Operating System & Odin Version: 
  MacOS 14.2.1
* Please paste `odin report` output:
        Odin: dev-2024-01:5961d4b3
        OS:   macOS Unknown (build: 23C71, kernel: 23.2.0)
        CPU:  ARM64
        RAM:  24576 MiB

**Comment by Kelimion** [comment] 2024-01-07 00:53
That's not a bug. An any is a pointer and a tag. You're returning a pointer to a stack frame that went out of scope.

**Closed by Kelimion** 2024-01-07 00:53 UTC
