### ISSUE TITLE
debug: slices can't be properly inspected

### ISSUE THREAD

**Issue by ryuukk** [odin-lang/Odin#2685] opened 2023-07-27 14:49 UTC
## Context

```
	Odin: dev-2023-07:1b36571
	OS:   Arch Linux, Linux 6.4.4-arch1-1
	CPU:  Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	RAM:  15867 MiB
```

Debuggers tried:

- qtcreator (gdb)
- gdb
- vscode (cpp extension)

OS i tried:

- linux

When building the following program:

```odin
package main

main::proc() {
    array: [42]int
    slice:= array[0:5]
    return
}

```

with: ``odin build main_odin.odin -file -debug``

Break at line: 6

## Expected Behavior

**1:** I should be able to inspect the ``array`` content in the watch menu of a debugger, from index 0 to 42

**2:** I should be able to inspect the ``slice`` content in the watch menu of a debugger, from index 0 to 5

## Current Behavior

**1:** works as expected

**2:** I can only see the pointer and the length

![image](https://github.com/odin-lang/Odin/assets/44361234/b77ed696-7012-40d4-929d-96f01d5a0982)

## What other languages do?

zig seems to handle this just fine, i can inspect slices/arrays

primitives:

![image](https://github.com/odin-lang/Odin/assets/44361234/ad3fc7b7-571d-409d-af84-1997bf06fe40)

structs:

![image](https://github.com/odin-lang/Odin/assets/44361234/79323ce2-8de3-4af9-976c-f6ab6837cb41)

**Comment by laytan** [comment] 2023-07-27 14:58
You are not missing anything, lldb also shows it like this.
I guess the debug symbols just see it as a pointer and there might be more you can give it so it knows its a type of array.

**Comment by JesseRMeyer** [comment] 2023-07-27 15:00
@laytan Correct.  This is a feature request.

You can see the elements with something like: `model.data, num_items`.

**Comment by hwchen** [comment] 2023-08-01 18:27
What's the way forward from here? I came up against this issue also. I'm not experienced w/ debuggers or c++, but willing to look into it if it helps.

**Comment by laytan** [comment] 2023-08-01 18:48
I suggest @ryuukk make a draft PR (or just link to the fork here) so we can see how far it has gotten and work from there.

I would guess the main difficulty is that a slice's length is not known at compile time, I vaguely remember llvm supporting some dynamic variable for this.

If you make a draft PR I can also spend some time looking into this.

**Comment by laytan** [comment] 2023-08-05 01:13
I have been looking into this and got as far as only needing the debug information to reference the `len` variable for the count.

For this, llvm has the `getOrCreateSubrange(int64_t Lo, Metadata *CountNode);` (https://github.com/llvm/llvm-project/blob/eb975626ac0a52ce832d7a34a6e4515a065233f2/llvm/include/llvm/IR/DIBuilder.h#L656).

You can give this subrange a reference to the length node of the slice and voila.

BUT, the llvm-c API does not expose this, it only exposes the `getOrCreateSubrange(int64_t Lo, int64_t Count);` version.
This version is defined here and is being used by Odin for arrays: https://github.com/llvm/llvm-project/blob/b0f4b6587a8e1044f6e4e1e117cc166586678ee5/llvm/include/llvm-c/DebugInfo.h#L1094

I do not think we can implement this feature without it being made available through llvm-c, I am not sure why it isn't there (maybe an oversight, or addition that was forgotten to be added to llvm-c).

**Comment by gingerBill** [comment] 2023-08-05 15:20
This is not a bug, per se. And I am closing this.

Your example compared to Zig is not even equivalent. When you do `x[0 .. 5]` in Zig, it becomes `*[5]T`, not a `[]T`, and thus not even the same kind of code.

I am not sure why I am having to explain the semantics of another language to you.

**Closed by gingerBill** 2023-08-05 15:20 UTC

**Comment by laytan** [comment] 2023-08-05 19:43
I agree that this is a nice feature request. I have some code here: https://github.com/odin-lang/Odin/commit/e2096e3c956235fb6304878caef61d82c0c8cd58 that partly implements this, but like my earlier comment says we are missing something in llvm-c for a dynamic count/length of the subrange.

The result of the above would look like this in the debugger: 

<img width="280" alt="Screenshot 2023-08-05 at 21 42 01" src="https://github.com/odin-lang/Odin/assets/20369598/22a40c9a-03b4-4546-85d9-685dd66289fb">
