### ISSUE TITLE
Mysterious Context Changes

### ISSUE THREAD

**Issue by dotbmp** [odin-lang/Odin#360] opened 2019-03-29 03:21 UTC
I can't seem to reproduce this, so I'm not really sure what the problem is. But the context is changing seemingly at random in my code, which results in some problems with pushed fields. This is evidenced by the changing pointer values in this screenshot:

![](https://i.imgur.com/J1kpBaj.png)

I'll give you the code for getting the context pointer if you'd like to use it yourself for debugging. I'm not worried about you patching this method of getting the pointer, as I'm directly pushing machine code into a virtual buffer and executing it, returning the value in the RCX register.

Muahahahaha.

**Comment by bpunsky** [comment] 2019-03-29 03:52
For whatever it's worth the difference between the pointers seems to be 1808 bytes consistently between builds, so the "other" context is coming from somewhere relatively far down the stack and not being popped properly.

I'm not explicitly doing anything with the context anywhere else in my code.

**Comment by gingerBill** [comment] 2019-03-31 10:24
@bpunsky How are you getting the context pointer in the first place?

**Comment by bpunsky** [comment] 2019-03-31 16:30
Creating a machine code proc that accepts no arguments and then returning the value of RCX as a context pointer. Not much you can do to thwart that 😛

**Comment by bpunsky** [comment] 2019-03-31 16:37
Anyway the problem of course is that pushing a context downstream of a proc should never affect contexts upstream. And I'm fairly sure no context pushes are even taking place downstream of this code, the only thing I'm doing with the context is using the temp allocator in some cases. So it's very strange that the context would change seemingly at random, and makes me wonder where else this might be happening in my code that I'm just not aware of because the substituted context also has a valid allocator.

**Comment by gingerBill** [comment] 2019-03-31 21:30
It could be a code gen bug. I'll have to check. Can you make minimum reproduceable piece of code?

**Comment by bpunsky** [comment] 2019-04-01 00:06
I've already tried and failed, but when I have a bit of time I'll see if I can get something to happen. If I can't reproduce it, though, extracting the relevant code from the codebase would be virtually impossible.

**Comment by ThisDrunkDane** [comment] 2020-02-06 14:22
@dotbmp Did you ever get this to happen again or can we close this?

**Comment by dotbmp** [comment] 2020-04-01 13:15
It happens consistently in the relevant code, but I can't reproduce it exactly

Someone else has mentioned this problem in the Odin Discord server recently

Has another bug been opened? Problem solved?

**Comment by gingerBill** [comment] 2020-04-01 14:02
I am going to close this because you are doing something that is very very dodgy in the first place, and I have no idea how to replicate this because there is no code for it.

I could allow an intrinsic to do this, if it is really necessary, but I will not yet.

**Closed by gingerBill** 2020-04-01 14:02 UTC
Labels: bug

**Comment by dotbmp** [comment] 2020-04-01 16:37
It's not about the ability to get the context pointer, just using that to illustrate the point. Somewhere *downstream* of this code, the context is changing (which it shouldn't be able to in any way) and thus the .user_data field is being nulled, which causes the program to not work right

I can still demonstrate the problem without the context pointer, in that the field gets nulled without touching the context in the caller, but this illustrates what's happening better (it's not just the field, it's the whole context being reassigned)

**Comment by gingerBill** [comment] 2020-04-02 11:59
@dotbmp Yes but can you at least show a basic example of this in order to fix it?
