### ISSUE TITLE
Implicit conversion at union initialization (not distinct enough)

### ISSUE THREAD

**Issue by vgen-me** [odin-lang/Odin#4234] opened 2024-09-12 00:39 UTC
## Context

Working on a small UI library in Odin + raylib.

        Odin:    dev-2024-08:55be3e60a
        OS:      Debian GNU/Linux 12 (bookworm), Linux 6.1.0-23-amd64
        CPU:     13th Gen Intel(R) Core(TM) i9-13900HX
        RAM:     31829 MiB
        Backend: LLVM 14.0.6

Relevant code is below. Here I declare a union of two distinct alias-types:
```
TypeA :: distinct i16
TypeB :: distinct f64

UnionC :: union
{
    TypeA,
    TypeB
}

test :: proc()
{
    a: TypeA
    b: TypeB
    c: UnionC

    // Compiles (expected, have type info)
    c = a
    c = b

    // Doesn't compile (expected, explicit conversion required)
    a = b
    b = a

   // Compiles (unexpected, ambiguous type)
   c = 8
}
```

## Expected Behavior

The code `c = 8` is ambiguous: the literal `8` can be represented by both `i16` (aka `TypeA`) and `f64` (aka `TypeB`). Since literal numbers are assumed to be untyped, there's no way to resolve the intended type of `padding` and this code should not compile.

## Current Behavior

The code compiles and runs. Literals with no decimal point are resolved to integer types, with decimal point - to float types. 
In many other languages this would be normal behaviour, but Odin enforces explicit conversions and  `distinct` prevents accidental implicit conversions in other cases. Union initialization with a number literal is an exception to this rule.

This may be legal in the current version of the language, but I would consider this a bug in the (unwritten) spec.
This behaviour is not clearly documented, surprising and will lead to subtle bugs down the line - as it did in my case. Since compiler didn't issue any warnings, I only found this by accident.

## Bugfix Proposal

Change the **_"Any of its variants to the `union`"_** conversion described in https://odin-lang.org/docs/overview/#implicit-type-conversions to require explicit conversion when two or more of the type variants may represent the number literal given.

**Comment by laytan** [comment] 2024-09-12 01:12
This is not a bug or unexpected  `8` becomes an `untyped integer` and will prefer assigning to an integer type over float types which makes this not ambiguous. Doing `8.` would make it an `untyped float` and assign to the float case.

**Closed by laytan** 2024-09-12 01:12 UTC

**Comment by vgen-me** [comment] 2024-09-12 02:08
I never said this was incorrect or illegal, I said it was unexpected. First, because Odin is normally very strict about conversions. Second, because it is not clearly documented. Here are relevant mentions of untyped ints from the docs:

> In the Odin type system, certain expressions will have an “untyped” type. An untyped type can implicitly convert to a “typed” type.
> I :: 42        // untyped integer, will implicitly convert to any numeric type (int, u32, f64, quaternion128 etc)`
https://odin-lang.org/docs/overview/#untyped-types

> Untyped integers -> all numeric related types that can represent them without truncation
https://odin-lang.org/docs/overview/#implicit-type-conversions

There's also [this](https://odin-lang.org/docs/faq/#what-is-the-type-of-x-in-x--123) FAQ section:

> 123 is an untyped integer literal: **_if the type has not been specified in the declaration_**, the default type for the “untyped” type will be chosen. In this case, x will be of type int.
> * if there is no default type for the untyped type, the type of the value cannot be inferred and this will cause an error.

This section talks about a case when no other type information is provided, e.g. in `x := 123`. In my example the types are provided and the literal can be represented by both.

Of course, adding your explanation to the docs will help a lot. But my point is different. This is not a bug, but its a bug-prone behaviour: it makes errors more likely. As far as I understand, the whole point of having explicit conversion and `distinct` types is to reduce the number of such errors. One could reasonably expect it to cover union initialization/assignment as well. Correct me if I'm wrong.

**Comment by laytan** [comment] 2024-09-12 11:20
> never said this was incorrect or illegal, I said it was unexpected.

I don't want to get into a useless argument here but you did say "this should not compile", and "bugfix proposal". You also said it was ambiguous which it is not.

Anyway, I see your point about it but untyped constants/literals are afaik designed to "just work" with whatever you assign to.
