### ISSUE TITLE
Assertion in malloc.c failed.

### ISSUE THREAD

**Issue by lonjil** [odin-lang/Odin#163] opened 2017-12-11 15:27 UTC
`mwe.odin`:
```go
Symbol :: struct {
	name: string,
	value: Element,
}
Cons :: struct {
	car, cdr: Element,
}
Element :: union {
	int,
	^Symbol,
	^Cons,
}
main :: proc() {
	symb := new(int); // can be any type
	cons := new(Cons);
	nums := new(int); // can be any type
}
```
The above produces this output:
```
mwe: malloc.c:2427: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```
On Linux. Bill said this might be an LLVM issue.

**Comment by gingerBill** [comment] 2017-12-12 09:24
Actually... I might know what the issue is and what I need to fix it. A fix will happen when the explicit-overloading branch is merged

**Closed** 2018-02-13 18:02 UTC
