### ISSUE TITLE
Bug in odin map

### ISSUE THREAD

**Issue by simonwashere** [odin-lang/Odin#2551] opened 2023-05-21 07:18 UTC
## Context

	Odin: dev-2023-05:0c352213
	OS:   macOS Unknown (build: 22F66, kernel: 22.5.0)
	CPU:  Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
	RAM:  16384 MiB

## Expected Behavior

The map data type should work

## Current Behavior

With some sequences of adding and removing values it seems to lose elements that should be there

### Steps to Reproduce

The simplest test case to reproduce it that I could come up with uses thousands of insert/remove steps and eventually the map reports an item is not present when it should be.

The attached test code is intended to verify the test data is accurate using an array then run the test using a map. For me the array code works fine then the map reports an error.

```
package main

import "core:fmt"
import "core:os"
import "core:slice"

read_data :: proc(file: os.Handle, $type: typeid) -> type {
	buffer: [size_of(type)]u8
	os.read(file, buffer[:])
	pointer := cast(^[size_of(type)]u8) raw_data(buffer[:])
	return transmute(type) pointer^
}

main :: proc() {
	TestItem :: struct { insert: bool, value: i64 }
	testItems: [dynamic]TestItem

	/* read in test data */
	fileName := "test.dat"
	file, error := os.open(fileName)
	if error != 0 do return
	itemCount := read_data(file, i32)
	for _ in 0 ..< itemCount {
		insert := read_data(file, bool)
		value := read_data(file, i64)
		append(&testItems, TestItem{insert, value})
	}
	os.close(file)

	fmt.printf("Item count: %v\n", itemCount)

	/* verify data is valid using an array */
	test_array: [dynamic]i64
	for item in testItems {
		idx, found := slice.linear_search(test_array[:], item.value)
		if item.insert == found {
			fmt.println("Array: BUG")
			break
		}
		if item.insert {
			append(&test_array, item.value)
		} else {
			unordered_remove(&test_array, idx)
		}
	}

	/* run the test on the map */
	test_map: map[i64]i32
	for item in testItems {
		if item.insert {
			test_map[item.value] = 1
		} else {
			if item.value not_in test_map {
				fmt.println("Map: BUG")
				break
			}
			delete_key(&test_map, item.value)
		}
	}

/*
	When I run this on my machine the output is:
		Item count: 6514
		Map: BUG
*/
}
```

[test.dat.zip](https://github.com/odin-lang/Odin/files/11523874/test.dat.zip)

**Comment by Kelimion** [comment] 2023-05-21 07:26
This is fixed using https://github.com/odin-lang/Odin/pull/2535, so while not pure a duplicate of #2515, it runs into the same issue.

**Closed** 2023-05-29 21:57 UTC
Labels: bug, replicated
