### ISSUE TITLE
macOS Catalina build fix

### ISSUE THREAD

**Issue by hasenj** [odin-lang/Odin#463] opened 2019-11-03 09:07 UTC
## Context

* Operating System: macOS Catalina

If you make the mistake of upgrading macOS to Catalina, your build might fail.

If you install llvm from homebrew, it will come with a version of clang that 1) overrides the system clang and 2) doesn't know where to find c headers

## How to fix

You need the following environment variables

```

# help homebrew's clang find the header files
export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

# suppress numerous warnings about stdlib.h
export CGO_CPPFLAGS="-Wno-nullability-completeness -Wno-expansion-to-defined"
```

**Comment by NotKyon** [comment] 2019-11-03 10:31
An alternate fix is to pass this to clang (modified build.sh)
```
-isysroot `xcrun --show-sdk-path`
```

**Comment by ThisDrunkDane** [comment] 2019-11-08 16:17
Have you tried upgrading your llvm installed from homebrew to 9.0.0? I am unable to reproduce this with that version

**Comment by ThisDrunkDane** [comment] 2020-01-06 16:00
Closing this and isn't really an Odin issue, if the topic keeps popping up we should probably write a note in the wiki about this. But we're by far not the only ones dealing with it

**Closed by ThisDrunkDane** 2020-01-06 16:00 UTC
