### ISSUE TITLE
Name collision between proc parameters and using-ed members is not reported.

### ISSUE THREAD

**Issue by lunaticLipid** [odin-lang/Odin#412] opened 2019-08-05 18:33 UTC
## Context

* Operating System: Windows 10
* Odin version/Commit: 5877017

```
package main

foo :: proc(a: int) -> int {
    using s: struct { a: int };
    s.a = a;
    return a;
}

main :: proc() {
    assert(foo(2) != 0);
}
```

## Expected Behavior

A warning about name collision like the one that shows up if the collision doesn't involve procedure parameters.

## Current Behavior

The code compiles. The assignment expression `s.a = a;` doesn't seem to do anything. `s.a` remains at its default 0 value.

**Comment by gingerBill** [comment] 2019-08-05 21:31
This new behaviour is due to the new procedure scoping rules. It's technically not a bug but an unintended feature.

**Comment by gingerBill** [comment] 2019-08-13 21:47
This has been fixed by modifying the `using` rules for procedure parameters.

**Closed by gingerBill** 2019-08-13 21:47 UTC
Labels: bug, design implementation
