### ISSUE TITLE
Compiler assert when calling `append` with non-existing identifiers

### ISSUE THREAD

**Issue by harold-b** [odin-lang/Odin#3533] opened 2024-05-05 03:00 UTC
## Context

The assertion in question:
```
src/error.cpp(59): Assertion Failure: `global_error_collector.curr_error_value_set.load() == true` Possible race condition in error handling system, please report this with an issue
```

System:
```
Odin:    dev-2024-05:17a01a81d
    OS:      macOS Sonoma 14.4 (build: 23E214, kernel: 23.4.0)
    CPU:     Apple M3 Max
    RAM:     65536 MiB
    Backend: LLVM 14.0.6
```
### To reproduce

With `bug.odin:`
```odin
package bug

main :: proc() {
    append(foo, bar)
}
```

```shell
git checkout 17a01a81d812793ee494d46885e6316c7cdd447e
build bug.odin -file -o:none -debug -thread-count:1
```

### Stack trace
```
odin!get_error_value() Odin/src/error.cpp:59)
odin!default_error_out_va(char const*, char*) Odin/src/error.cpp:186)
odin!error_line_va(char const*, char*) Odin/src/error.cpp:450)
odin!error_line(char const*, ...) Odin/src/error.cpp:619)
odin!check_call_arguments_proc_group(CheckerContext*, Operand*, Ast*)::$_113::operator()() const Odin/src/check_expr.cpp:6590)
odin!check_call_arguments_proc_group(CheckerContext*, Operand*, Ast*) Odin/src/check_expr.cpp:6626)
odin!check_call_arguments(CheckerContext*, Operand*, Ast*) Odin/src/check_expr.cpp:6825)
odin!check_call_expr(CheckerContext*, Operand*, Ast*, Ast*, Slice<Ast*> const&, ProcInlining, Type*) Odin/src/check_expr.cpp:7508)
odin!check_expr_base_internal(CheckerContext*, Operand*, Ast*, Type*) Odin/src/check_expr.cpp:10602)
odin!check_expr_base(CheckerContext*, Operand*, Ast*, Type*) Odin/src/check_expr.cpp:10732)
odin!check_expr_stmt(CheckerContext*, Ast*) Odin/src/check_stmt.cpp:2133)
odin!check_stmt_internal(CheckerContext*, Ast*, unsigned int) Odin/src/check_stmt.cpp:2484)
odin!check_stmt(CheckerContext*, Ast*, unsigned int) Odin/src/check_stmt.cpp:583)
odin!check_stmt_list(CheckerContext*, Slice<Ast*> const&, unsigned int) Odin/src/check_stmt.cpp:108)
odin!check_proc_body(CheckerContext*, Token, DeclInfo*, Type*, Ast*) Odin/src/check_decl.cpp:1664)
odin!check_proc_info(Checker*, ProcInfo*, PtrMap<Ast*, ExprInfo*>*) Odin/src/checker.cpp:5644)
odin!check_proc_info_worker_proc(void*) Odin/src/checker.cpp:5849)
odin!thread_pool_wait(ThreadPool*) Odin/src/thread_pool.cpp:119)
odin!thread_pool_wait() Odin/src/main.cpp:25)
odin!check_procedure_bodies(Checker*) Odin/src/checker.cpp:5895)
odin!check_parsed_files(Checker*) Odin/src/checker.cpp:6312)
odin!main Odin/src/main.cpp:2757)
start (Unknown Source:0)
```

**Comment by Feoramund** [comment] 2024-05-05 06:09
Duplicate of #3519.

**Comment by gingerBill** [comment] 2024-05-07 10:22
Fixed

**Closed by gingerBill** 2024-05-07 10:22 UTC
